#!/bin/bash
export CURRENT_SHELL=$(ps h -p $$ -o args='' | cut -f1 -d' ')
if [[ "${CURRENT_SHELL}" != *"bash" ]]; then
	echo "Please run with bash instead of ${CURRENT_SHELL}."
	exit
fi
# Locate the project folder
OIFS="$IFS"
echo "${PWD}" | IFS='/' read -r -a paths
let fsPointer=$((${#paths[@]} - 1))
IFS='/'
while [ "$fsPointer" -ge 0 ]; do
	fsPath="${paths[*]:0:$((fsPointer + 1))}"
	fsPath=${fsPath:-/}
	if [ -f "$fsPath/shx" ] && [ -d "$fsPath/sh" ] ; then
		cd "$fsPath"
		break
	fi
	fsPointer=$(($fsPointer - 1))
done
IFS="$OIFS"
export PATH=$PATH:./:./sh
# Command parsing
arg="$@"
args=( "$@" )
if [ "$arg" == "" ] ; then
	echo -e "\033[1;37mshx 0.2\033[0m"
	echo "All available actions:"
	ls -1 sh | while IFS= read -r file; do
		echo "${file/.sh/}"
	done
elif [ -e "sh/$1.sh" ] ; then
	bash "sh/$1.sh" "${args[@]:1}"
elif [ -e "sh/$1" ] ; then
	bash "sh/$1" "${args[@]:1}"
else
	echo "No action found as \"$1\". Command: \"${args[@]:1}\"".
fi
exit
